### ISSUE TITLE
Postmanワークスペースの設置

### ISSUE THREAD

**Issue by KleinChiu** [hal-tokyo-cello/cello-functions#17]
Postmanをモックサーバとして運用する。

フロントエンドチームは、
モックサーバにリクエストをすることでアクセス検証をする。

バックエンドチームは、
リクエストとコレクションを実行することで、実装内容のアクセス検証をする。

- [x] ワークスペース作成
- [x] バックエンドメンバーを招待
- [ ] 環境変数を設定
- [x] コレクションを作成
- [x] モックサーバのURLをフロントエンドチームに公開

**Comment by CornerSyrup** [comment]
現在の設置で終わり、API設計ながら追って設定をする
