### ISSUE TITLE
アバター進化について

### ISSUE THREAD

**Issue by reone19** [hal-tokyo-cello/cello-functions#36]
バックチームでアバターの進化に関してまとめます。

確認事項
- [x] 使用APIは `/avatars/evolution` を使用します。
- [x] レベルの数値表現は総獲得経験値 `totalExp` 基づいて関数で処理します。
- [x] 進化可能レベルは「Level：１０」にしました。
- [x] 関数で算出したレベルの数値か総獲得経験値 `totalExp` 量に基づいて進化可能かを判定します。
- [x] 以下、ER図のユーザーテーブルとアバターテーブルを1対1に変更しました。また、念のため進化判定のカラムを追加しました。
![image](https://cdn.discordapp.com/attachments/980668396867837972/996948463050821773/ER.png)

- [x] 進化は強制とします。
- [x] 画面の遷移は以下を想定
![image](https://user-images.githubusercontent.com/66284670/178881903-9a5e18ec-0fab-4942-ad3b-4f7224532b5d.png)

- [x] 「Level：１０」に到達した時の専用モーダルが必要か検討しています。
- [x] 蛇足、専用モーダルが必要な場合、出力モーダルの変更用に判定処理を入れる必要があると考えます。

**Comment by CornerSyrup** [comment]
コアライブラリの`Avatar`にも進化済みのフラグを持たせたほうがいい？
進化可能かの判定をコアライブラリに持たせたほうがいい？

**Comment by reone19** [comment]
@nakaosan どうでしょうか？
私の認識では、従来のドメイン部分の使い方だと
cello-functionsではコアライブラリーの関数を読み込んだうえでの処理を書いている認識ですので、進化フラグをどちらに持たせるかというと、コアライブラリーに関数としてまとめるほうがきれいに感じます。

進化可能かフラグ、進化済みフラグはどちらも規模は大きくない処理なのでcello-functionsで持たせてもいい気もしますが

**Comment by nakaosan** [comment]
@KleinChiu 
私もフラグをコアライブラリに持たせるのはありがたいです。

**Comment by CornerSyrup** [comment]
進化可能フラグは計算のみなので、DBに影響はない；
進化済みフラグは保存ですが、現在のER図では対応できると思います、`IAccountRepository`には更新があるかも

**Comment by reone19** [comment]
進化フラグに関しては、ER図に追記したものですが、一応残しておきます。

**Comment by reone19** [comment]
他にここで共有するべきことがないのであれば、このissueを閉じようと考えています。
1日待ちます。
